version: '3.9'

services:

  server:
    build: .
    container_name: "tabbled-server"
    restart: always
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - pg_data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}

volumes:
  pg_data:
    external: true